name: tstst
favicon: null
layout_spectrum: 0.05198832391761243
typography_spectrum: 0.225975024048239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.11692960700020194
  lightness: 0.6901858923956752
  saturation: 0.7930936175398529
  rhythmicContrast: 0.340990238590166
purpose: []
