name: tstst
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2307
title: Testsite for testing The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fcfe'
    - '#000000'
    - '#00289f'
    - '#64a1c1'
    - '#005ec5'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
